### ISSUE TITLE
Tag the PR for dependabot PR's

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-pr-to-work-item#10]
create a special tag for dependabot pr's

**Comment by DaveBurnisonMS** [comment]
My humble suggestion would be to use "Security Alert" for the tag. Then in the future when other issues, PRs, work items get created that are related to CodeQL they can also be tagged with "Security Alert". This will allow Azure Boards users to consistently find work items that are related to any type of security issue.
