### ISSUE TITLE
PR work item not created

### ISSUE THREAD

**Issue by dotnetspark** [danhellem/github-actions-pr-to-work-item#13]
@danhellem for some reason the action ran successfully (first), then [failed](https://github.com/ylr-research/OceanSimulator/actions/workflows/pr2ab.yml), but it didn't create the PR work item. I'm not sure if could be related to the template I'm using (Basic).

**Comment by danhellem** [comment]
@ylr-research You should either customize your process and create a "Pull Request" WIT or change the action configuration to use the "Issue" WIT.
