### ISSUE TITLE
Can we submit the 'Closed Date' field when closing an issue?

### ISSUE THREAD

**Issue by riserrad** [danhellem/github-actions-pr-to-work-item#22]
As of today, when we close an issue on GitHub, the work item on AzDO end goes to the desired "Closed" state, but it complains about the "Closed Date" field being empty:

```
Field 'Closed Date' cannot be empty.
```

**Comment by danhellem** [comment]
You probably have some kind of rule that is taking place to force you to enter a closed date. You could certainly fork the repo and add some code to include the closed date when closing the PR.
