### ISSUE TITLE
Error: Cannot read property 'replace' of null - when PR description is empty

### ISSUE THREAD

**Issue by riserrad** [danhellem/github-actions-pr-to-work-item#23]
When submitting a PR with no description - or no comments - the Action fails with this error.

I tried forking the repo and protecting the two calls for `.replace` I've found:

- main.ts / getWebHookPayLoad
- patch-documents.ts / editedPatchDocument

But no luck. I also tried to change the `catch` of main.ts / run to output the stack, but it didn't change the output. 

It looks to me that this is happening even before the main / run code is hit.

**Comment by danhellem** [comment]
I just tested this out on a new project and repo. The cod works fine. I think what you have is an issue with one of your env settings. Most likely the org name, project name, or your PAT is bad.
