### ISSUE TITLE
Add area path option to env variables

### ISSUE THREAD

**Issue by danhellem** [danhellem/github-actions-pr-to-work-item#3]

**Comment by shauke** [comment]
`ado_area_path` and `ado_iteration_path` as in https://github.com/danhellem/github-actions-issue-to-work-item would be very nice.

**Comment by danhellem** [comment]
Thanks @shauke, now that a couple more folks are requesting it, i will get it done!

**Comment by danhellem** [comment]
I updated master and created a new pre-release version for this. I did not have time to test so please test in production and let me know if you have troubles.

**Comment by shauke** [comment]
Is changing the documentation (README.md) really enough to add this functionality or are I missing something?
It didn't work as expected either. 😉 

And what about the `ado_iteration_path`? This would make it even more like the Issus Sync Action. 😍

**Comment by danhellem** [comment]
you are missing something. Added the variable and the supporting code.

not going to add iteration path. Sorry

**Comment by danhellem** [comment]
@shauke actually try again. I somehow missed committing the code. Should be all there now.

**Comment by shauke** [comment]
Tested it an now it works as expected. Thanks a lot. 👍 

Can I wish for adding the iteration path in a separate GitHub issue or is it a general issue that this will/can never be added for the pull request sync action?

**Comment by danhellem** [comment]
Sorry, I have no plans to add iteration path to the action. If you want to do that, you would need to fork the repo and do it on your own.
